user_name: name
password: password

root_path: C:\Users\YourName\Documents\KIT

classes:
  la:
    name: Lineare Algebra 1
    path: Lineare Algebra I
    assignment:
      name: Übungen
      format: Blatt$$

  gbi:
    name: Grundbegriffe der Informatik (2018/2019)
    path: Grundbegriffe der Informatik
    assignment:
      name: Übungsblätter
      format: $$-aufgaben

  prg:
    name: Programmieren
    path: Programmieren
    assignment:
      name: Übungen
      format: Übungsblatt $/assignment$$

  hm:
    name: Höhere Mathematik 1
    link: http://www.math.kit.edu/iana2/edu/hm1info2018w/de
    path: Höhere Mathematik I
    assignment:
      format: Blatt $